### ISSUE TITLE
v3 Breaks Typescript Build

### ISSUE THREAD

**Issue by LoganArnett** [JustinBeckwith/retry-axios#193]
I am not entirely sure what the issue is but on v2.6.0 everything works so I reverted back to that version but when I attempted to build the same project o v3.0.0 with a node version of v16+ the build succeeds with no errors but when the code is run I get this error:

```
"require() of ES Module /var/task/node_modules/retry-axios/build/src/index.js from /var/task/utils/axios.js not supported.\nInstead change the require of index.js in /var/task/utils/axios.js to a dynamic import() which is available in all CommonJS modules."
```

I attempted to change the import structure between both 
```js
import rax from 'retry-axios';

// and

 import * as rax from 'retry-axios';
```

And still got the same error.

Just curious if there is something obvious I need to do to be able to upgrade to v3.

**Comment by zymotik** [comment]
I have an error that I believe it related when using the Vue 2.6 build tools. I see a message in the console "This dependency was not found" with the suggestion "To install it, you can run: npm install --save retry-axios"

```bash
 ERROR  Failed to compile with 1 error

This dependency was not found:

* retry-axios in ./src/backend/tracking/matomo-tracking-client.ts

To install it, you can run: npm install --save retry-axios
```
Versions:
TypeScript version 4.3.4
retry-axios 3.0.0
VueJs 2.6.14
@vue/cli-service 4.5.13

**Comment by ashkanjj** [comment]
I'm getting the same, happy to create a reproducible setup in somewhere like codesandbox if anyone is happy to look into this?

**Comment by leefsmp** [comment]
Same here, getting error `ERR_REQUIRE_ESM` which seems to be related to the way lib is being exported. [](https://github.com/standard-things/esm/issues/868). Reverting to 2.6.0 works thanks.

**Comment by leopucci** [comment]
![image](https://user-images.githubusercontent.com/38509299/180463454-bbc03e2f-bb7a-4bb6-bdc7-ee49e333dd8c.png)

**Comment by DavidHe1127** [comment]
We see a different error
```
    Details:

    /work/node_modules/retry-axios/build/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from 'axios';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 | import * as k8s from '@kubernetes/client-node';
      4 | import axios, { AxiosError } from 'axios';
    > 5 | import * as rax from 'retry-axios';
        | ^
      6 | import * as https from 'https';
      7 |
      8 | // The `waitForStatefulset` checks are necessary because Pulumi does not

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/tests/system/prometheus.spec.ts:5:1)
```

Adding config below to transform that file doesn't work

```
  "transformIgnorePatterns": [
    "node_modules/(?!retry-axios/build/src/index)"
  ]
```

**Comment by hisham** [comment]
+1

**Comment by willbui256resi** [comment]
+1

**Comment by vlepot** [comment]
I encountered the same issue on an application compiled from TypeScript to CommonJS.
I propose the following fix so that it can be used as both CJS and ES module.
